language: node_js
node_js: '10.6'
cache:
  yarn: true
before_install:
- curl -o - -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn --frozen-lockfile --non-interactive
jobs:
  include:
  - stage: test
    before_script:
    - npm i codecov -g
    script:
    - yarn run lint
    - yarn run test:unit
  - stage: build
    script:
    - yarn run bundle
#deploy:
#  provider: releases
#  api_key:
#    secure: $API_KEY
#  file: dist/vue-hotel-datepicker.js
#  on:
#    repo: digital-drifter/vue-hotel-datepicker
